# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
platform :ios, '8.0'
use_frameworks!

target 'JKAddressBook' do
	pod 'Kanna','~> 1.0.0'
end

target 'JKAddressBookTests' do
	pod 'Kanna', '~> 1.0.0'
end

target 'JKAddressBookUITests' do

end

